import type { Game } from "./game";
import type { Action } from "./route";

/** Position of an island right now. */
const at = (g: Game, id: string) => g.islandPosition(g.island(id)!);

/**
 * The intended solution of every chapter, played through ordinary inputs.
 * Tests run each one to the observatory with all three seeds.
 */
export const ROUTES: Action[][] = [
  // 0. The waking garden
  [
    { go: 4.5 },
    { jump: 8, on: "a2" },
    { go: 11 },
    { jump: 15, on: "a3" },
    { go: 18 },
    { fold: true },
    { jump: 21, on: "b1" },
    { go: 25 },
    { jump: 28, on: "b2" },
    { jump: 30, tap: false },
    { go: 33 },
    { jump: 36, on: "c1" },
    { go: 38.2 },
    { expect: (g) => g.mode === "2d", why: "still folded at the rock" },
    { fold: true },
    { go: 40, z: -3 },
    { go: 45, z: 0 },
    { jump: 48, on: "d1" },
    { go: 51 },
    { fold: true },
    { jump: 55, on: "d2" },
    { go: 58 },
    { jump: 62, on: "e1" },
    { go: 68 },
  ],
  // 1. The hidden courtyard
  [
    { go: 4.5 },
    { jump: 8, on: "a2" },
    { go: 10, z: -3.6 },
    { go: 14, z: -3.6 },
    { go: 16.5, z: 0 },
    { fold: true },
    { jump: 20, on: "b1" },
    { go: 24.5 },
    { jump: 28, on: "b2" },
    { go: 30.6 },
    { fold: true },
    { go: 30.6, z: -16 },
    { go: 36.5, z: -16 },
    { go: 36.5, z: -9 },
    { jump: 40, z: -6, on: "c0" },
    { jump: 44, z: 3, on: "c1" },
    { go: 46, z: 3 },
    { go: 50.5, z: 3 },
    { fold: true },
    { jump: 55, on: "d1" },
    { go: 58 },
    { jump: 61, on: "d2" },
    { go: 64.5 },
    { jump: 68, on: "e1" },
    { go: 69.8 },
    { fold: true },
    { go: 69.8, z: 2.5 },
    { go: 74, z: 2.5 },
    { go: 78.5 },
    { fold: true },
    { jump: 81.5, on: "f1" },
    { jump: 81.5 },
    { go: 82.5 },
    { jump: 85.5, on: "f2" },
    { go: 84.3 },
    { jump: 81.5, on: "f1" },
    { go: 80.3 },
    { jump: 77, on: "e1" },
    { go: 76 },
  ],
  // 2. The tide engine
  [
    { go: 4.6 },
    { until: (g) => at(g, "a2").x - 1.5 < 6.2, why: "the ferry docks" },
    { jump: 8, on: "a2" },
    { until: (g) => at(g, "a2").x > 11.8, why: "the ferry crosses" },
    { jump: 16.5, on: "a3" },
    { go: 22.6 },
    { until: (g) => at(g, "b1").z > -0.6, why: "the depth ferry comes near" },
    { jump: 26.6, z: 0, on: "b1" },
    { until: (g) => at(g, "b1").z < -10.6, why: "the depth ferry reaches the far island" },
    { jump: 31, z: -11, on: "b2" },
    { go: 35.5 },
    { fold: true },
    { jump: 39.5, on: "c1" },
    { go: 61 },
    { go: 65.5 },
    { until: (g) => Math.abs(at(g, "d1").y - 1) < 0.25 && Math.cos(g.time * 0.8) > 0, why: "the lift rises past the ledge" },
    { jump: 69.5, on: "d1" },
    { until: (g) => at(g, "d1").y > 3.9, x: 70, why: "the lift nears the top" },
    { jump: 73.5, on: "d2" },
    { expect: (g) => g.collected.has("s2"), why: "seed caught from the lift" },
    { go: 77.6 },
    { jump: 81, on: "e1" },
    { go: 87 },
  ],
  // 3. The violet archive
  [
    { go: 4.5 },
    { jump: 8.5, on: "a2" },
    { go: 9, z: 2.6 },
    { go: 17.5, z: 2.6 },
    { go: 17.5, z: -2.5 },
    { go: 18.5 },
    { jump: 22.5, on: "b1" },
    { fold: true },
    { go: 26.5 },
    { until: (g) => g.wallHeight(g.level.walls[0]) < 0.05, why: "the gate sinks" },
    { go: 31 },
    { jump: 33, on: "c1" },
    { go: 32.7 },
    {
      until: (g) => {
        const s = g.level.sentinels[1];
        const now = g.sentinelPosition(s).x;
        return now < 36.3 && now < g.sentinelPosition(s, g.time - 0.05).x;
      },
      why: "the far sentinel comes close",
    },
    { jump: 38.2 },
    { go: 39.6 },
    { expect: (g) => g.collected.has("s2"), why: "seed taken under the sentinel's path" },
    { fold: true },
    { go: 39.6, z: 2.5 },
    { jump: 44, z: 2.6, on: "d1" },
    { go: 46.5, z: 2.6 },
    { expect: (g) => g.lit.has("L2"), why: "the lantern behind the sunwall is lit" },
    { go: 48.5, z: 0 },
    { until: (g) => g.islandPresence(g.island("d2")!) > 0.95, why: "the bridge forms" },
    { go: 61 },
    { jump: 64, on: "d3" },
    { go: 67.6 },
    { fold: true },
    { until: (g) => g.sentinelPosition(g.level.sentinels[2]).y < 1.6, why: "the gap sentinel dips" },
    { jump: 72.5, on: "e1" },
    { go: 78 },
  ],
  // 4. The night crossing
  [
    { go: 4.5 },
    { jump: 8.5, on: "a2" },
    { go: 14.6 },
    { jump: 17, on: "g1" },
    { jump: 20, on: "g2" },
    { jump: 23, on: "h1" },
    { go: 34.5 },
    { go: 35.25, tol: 0.1 },
    { fold: true },
    { expect: (g) => g.player.grounded && g.player.support === "sb", why: "standing on starlight" },
    { go: 45 },
    { fold: true },
    { go: 52.3 },
    { jump: 58, from: 52.4, fold: 0.18, on: "c1" },
    { go: 63 },
    { jump: 67, on: "d1" },
    { expect: (g) => g.mode === "2d", why: "still folded on the far row" },
    { fold: true },
    { go: 67, z: -10.2 },
    { go: 71.4, z: -10.2 },
    { jump: 75, z: -10.5, on: "gz" },
    { go: 75, z: -0.8 },
    { jump: 79, z: 0, on: "e1" },
    { go: 84.5 },
  ],
  // 5. The last observatory
  [
    { go: 4.6 },
    { until: (g) => at(g, "a2").x - 1.5 < 6.7, why: "the ferry docks" },
    { jump: 9, on: "a2" },
    { fold: true },
    { until: (g) => at(g, "a2").x > 12.6, why: "the ferry crosses" },
    { jump: 18, on: "a3" },
    { go: 23 },
    { jump: 27, on: "b1" },
    { go: 29.8 },
    { fold: true },
    { go: 29.8, z: -7.4 },
    { go: 35.5, z: -7.4 },
    { go: 35.5, z: -11 },
    { jump: 40, z: -11, on: "c1" },
    { fold: true },
    { go: 41 },
    { until: (g) => g.wallHeight(g.level.walls[1]) < 0.05, why: "the gate sinks" },
    { fold: true },
    { go: 44.5, z: -8 },
    { jump: 48.5, z: -8, on: "d1" },
    { go: 56.4, z: -8.5 },
    { go: 56.4, z: -11 },
    { jump: 59, on: "e1" },
    { jump: 62, on: "e2" },
    { jump: 65.5, on: "e3" },
    { go: 76.8 },
    { go: 77.25, tol: 0.1 },
    { fold: true },
    { go: 87 },
    { fold: true },
    { go: 94.4 },
    { jump: 99, from: 94.5, fold: 0.15, on: "g2" },
    { go: 100.5 },
    { expect: (g) => g.collected.has("s1"), why: "the midair seed" },
    { fold: true },
    { go: 102, z: 8 },
    { until: (g) => at(g, "h1").z > 6.6, x: 102, why: "the depth ferry comes near" },
    { jump: 105.8, z: 7, on: "h1" },
    { until: (g) => at(g, "h1").z < -6.6, x: 106, why: "the depth ferry reaches the far side" },
    { jump: 110.5, z: -8, on: "h2" },
    { go: 113.5, z: -9 },
    { until: (g) => g.islandPresence(g.island("i1")!) > 0.95, why: "the bridge forms" },
    { go: 115.5, z: -9 },
    { until: (g) => g.sentinelPosition(g.level.sentinels[1]).x > 123, why: "the bridge sentinel passes" },
    { go: 126 },
    { jump: 129.5, z: -6, on: "j1" },
    { go: 137, z: -2 },
  ],
];
